name: secure_task_manager
description: Secure, offline-first task manager with clean architecture.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.2
  lottie: ^3.1.2
  local_auth: ^3.0.0
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.0.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/task_animation.json
    - assets/lottie/plan.json
    - assets/lottie/secure.json
    - assets/lottie/productive.json
